title: "Efficient Long-Horizon Learning for Learned Optimization"
description: "ELO: an efficient meta-training algorithm for learned optimization that scales to long inner horizons and surpasses hand-designed optimizers."
url: "https://xiaol827.github.io"
baseurl: "/ELO-page"
theme: null
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
